sik/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from sik.models import User, Tsk_belumnikah, Tsk_tidakmampu, Tpermohonan, Tpenduduk, Tinformasi
from sik import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sik import app
from PIL import Image
# ==============================================================================================
from sik.forms import Registrasi_F, Login_F, Sk_belumnikah_F, Sk_tidakmampu_F, Kategorisurat_F, Penduduk_F, Update_Account_F, Informasi_F
# ==============================================================================================
# from flask_admin.contrib.sqla import ModelView

vmahasiswa = Blueprint('vmahasiswa', __name__)


@vmahasiswa.route("/")
@vmahasiswa.route("/home")
def landing():
	penduduk = Tpenduduk.query.all()
	informasi = Tinformasi.query.all()
	return render_template("landing_page.html", title='Home', penduduk=penduduk, informasi=informasi)

@vmahasiswa.route("/surat/permohonan", methods=['GET','POST'])
@login_required
def suratpermohonan():
	form=Kategorisurat_F()
	if form.validate_on_submit():
		kategorisurat = Tpermohonan(nama=form.nama.data, no_hp=form.no_hp.data, kategori=form.kategori.data, pemohon=current_user)
		db.session.add(kategorisurat)
		db.session.commit()
		flash('Data berhasil ditambahkan','success')
		return redirect(url_for('vmahasiswa.pilihkategori'))
	return render_template("surat_permohonan.html", title="Surat Permohonan", form=form, Legend='Surat Permohonan', kategorisurat='kategorisurat')

@vmahasiswa.route("/pilih/kategori/surat")
def pilihkategori():
	return render_template("pilih_kategori.html")

# ============================================================================================
@vmahasiswa.route("/registrasi", methods=['GET', 'POST'])
def registrasi():
	if current_user.is_authenticated:
		return redirect(url_for('vmahasiswa.landing'))
	form = Registrasi_F()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Akun {form.username.data} Berhasil di Tambahkan, Silahkan Login', 'success')
		return redirect(url_for('vmahasiswa.loginuser'))
	return render_template("daftar.html", title="Registrasi", form=form)

# ==============================================================================================
@vmahasiswa.route("/loginuser", methods=['GET', 'POST'])
def loginuser():
	if current_user.is_authenticated:
		return redirect(url_for('vmahasiswa.base'))
	form = Login_F()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page= request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('vmahasiswa.landing'))
		else:
			flash('Login failed...!!!, Periksa Kembali Email dan Password Anda', 'warning')
	return render_template("login.html", title="Login", form=form)

# ===============================================================================================
@vmahasiswa.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('vmahasiswa.landing'))

# =============================================================================================
@vmahasiswa.route("/sk_belumnikah", methods=['GET','POST'])
@login_required
def sk_belumnikah():
	form=Sk_belumnikah_F()
	if form.validate_on_submit():
		sk_belumnikah = Tsk_belumnikah(nama=form.nama.data, ttl=form.ttl.data, jenis_kelamin=form.jenis_kelamin.data, status_perkawinan=form.status_perkawinan.data, 
        	agama=form.agama.data, kewarganegaraan=form.kewarganegaraan.data, pekerjaan=form.pekerjaan.data, alamat=form.alamat.data)
		db.session.add(sk_belumnikah)
		db.session.commit()
		flash('Data berhasil ditambahkan','Sukses')
		return redirect(url_for('vmahasiswa.suratpermohonan'))
	return render_template("sk_belumnikah.html",  form=form, sk_belumnikah='sk_belumnikah')

# =============================================================================================
@vmahasiswa.route("/sk_tidakmampu", methods=['GET','POST'])
@login_required
def sk_tidakmampu():
	form=Sk_tidakmampu_F()
	if form.validate_on_submit():
		sk_tidakmampu = Tsk_tidakmampu(nama=form.nama.data, nik=form.nik.data, ttl=form.ttl.data, jenis_kelamin=form.jenis_kelamin.data, agama=form.agama.data, 
			pekerjaan=form.pekerjaan.data, kewarganegaraan=form.kewarganegaraan.data, alamat=form.alamat.data)
		db.session.add(sk_tidakmampu)
		db.session.commit()
		flash('Data berhasil ditambahkan','Sukses')
		return redirect(url_for('vmahasiswa.suratpermohonan'))
	return render_template("sk_tidakmampu.html",  form=form, sk_tidakmampu='sk_tidakmampu')

# =============================================================================================
def simpan_foto(form_foto):
	random_hex = secrets.token_hex(8)
	f_name, f_ext = os.path.splitext(form_foto.filename)
	foto_fn = random_hex + f_ext
	foto_path = os.path.join(app.root_path, 'sik/static/foto', foto_fn)
	form_foto.save(foto_path)
	return foto_fn
	# add in p.9
	output_size =(125,125)
	j = Image.open(form_foto)
	j.thumbnail(output_size)
	j.save(foto_path)
	return foto_fn

@vmahasiswa.route("/account", methods=['GET','POST'])
@login_required
def akun():
	form=Update_Account_F()
	# ============add in p.9===========
	if form.validate_on_submit():
		# save foto profil
		if form.foto.data:
			file_foto = simpan_foto(form.foto.data)
			current_user.img = file_foto
		# save db
		current_user.username=form.username.data
		current_user.email=form.email.data
		db.session.commit()
		flash('Akun ini berhasil di update!','success')
		return redirect(url_for('vmahasiswa.akun'))
	elif request.method == 'GET':
		form.username.data=current_user.username
		form.email.data=current_user.email
	# ============add in p.9===========
	img = url_for('static', filename='foto/' + current_user.img)
	return render_template("akun.html", title="Account", img=img, form=form)

sik/templates/akun.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>ACCOUNT</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
<!-- 	<link rel="icon" type="image/png" href="{{url_for('static', filename='akun/images/icons/favicon.ico')}}"/> -->
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/vendor/bootstrap/css/bootstrap.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/fonts/iconic/css/material-design-iconic-font.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/vendor/animate/animate.css')}}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/vendor/css-hamburgers/hamburgers.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/vendor/animsition/css/animsition.min.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/vendor/select2/select2.min.css')}}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/vendor/daterangepicker/daterangepicker.css')}}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/css/util.css')}}">
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='akun/css/main.css')}}">

<!--CSS FOR HEADER-->
	<link rel="stylesheet" href="{{url_for('static', filename='assets/css/main.css')}}" />
	<noscript><link rel="stylesheet" href="{{url_for('static', filename='assets/css/noscript.css')}}" /></noscript>

</head>
<body>
	<header id="header">
		<h1><a href="{{url_for('vmahasiswa.landing')}}">Simike Gambesi</a></h1>
		<nav id="nav">
			<ul>
				<li class="special">
					<a href="#menu" class="menuToggle"><span>Menu</span></a>
					<div id="menu">
						<ul>
							<li><a href="{{url_for('vmahasiswa.landing')}}">Home</a></li>
							{% if current_user.is_authenticated %}
								<li><a href="{{url_for('vmahasiswa.suratpermohonan')}}">Surat Permohonan</a></li>
								<li><a href="{{url_for('vmahasiswa.akun')}}">Account</a></li>
								<li><a href="{{url_for('vmahasiswa.logout')}}">Logout</a></li>
							{% else %}
								<li><a href="{{url_for('vmahasiswa.registrasi')}}">Sign Up</a></li>
								<li><a href="{{url_for('vmahasiswa.loginuser')}}">Log In</a></li>
							{% endif %}
						</ul>
					</div>
				</li>
			</ul>
		</nav>
	</header>

<section id="one" class="wrapper style2 special">
	<div class="inner">
		<div class="major">
			<img class="login100-form-avatar rounded-circle account-img" src="{{ img }}"><br />
			<div class="media-body">
				<p class="text-secondary">{{current_user.username}}</p>
				<p class="text-secondary">{{current_user.email}}</p>
			</div>
		</div>
<!-- ==================BATAS next copyan dari file registrasi================= -->
		<form action="" method="POST" enctype="multipart/form-data" class="login100-form validate-form">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<div class="form-group wrap-input100 validate-input m-t-30 m-b-20" align="left">
					{{ form.username.label(class="form-control-label") }}

					<!-- =========ERROR=========== -->
					{% if form.username.errors %}
					{{ form.username (class='form-control form-control-lg is-invalid')}}
					
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
						<span> {{ error }}</span>
						{% endfor %}

					</div>
					{% else %}
					{{ form.username(class='form-control form-control-lg') }}
					{% endif %}
				</div>
				<!--=================================================-->
				<div class="form-group wrap-input100 validate-input m-t-30 m-b-20" align="left">
					{{ form.email.label(class="form-control-label") }}

					<!-- =========ERROR=========== -->
					{% if form.email.errors %}
					{{ form.email (class='form-control form-control-lg is-invalid')}}
				
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span> {{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.email(class='form-control form-control-lg') }}
					{% endif %}
				</div>
				
					<div class="form-group" align="left">
						{{ form.foto.label() }}
						{{ form.foto(class='form-control-file') }}
						{% if form.foto.errors %}
							{% for error in form.foto.errors %}
								<span class="text-danger">{{error}}</span></br>
							{% endfor %}
						{% endif %}
					</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>  
	</div>
</section>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='akun/vendor/jquery/jquery-3.2.1.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='akun/vendor/animsition/js/animsition.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='akun/vendor/bootstrap/js/popper.js')}}"></script>
	<script src="{{url_for('static', filename='akun/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='akun/vendor/select2/select2.min.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='akun/vendor/daterangepicker/moment.min.js')}}"></script>
	<script src="{{url_for('static', filename='akun/vendor/daterangepicker/daterangepicker.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='akun/vendor/countdowntime/countdowntime.js')}}"></script>
<!--===============================================================================================-->
	<script src="{{url_for('static', filename='akun/js/main.js')}}"></script>

<!--SCRIPT FOR HEADER-->
	<script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
	<script src="{{url_for('static', filename='assets/js/jquery.scrollex.min.js')}}"></script>
	<script src="{{url_for('static', filename='assets/js/jquery.scrolly.min.js')}}"></script>
	<script src="{{url_for('static', filename='assets/js/browser.min.js')}}"></script>
	<script src="{{url_for('static', filename='assets/js/breakpoints.min.js')}}"></script>
	<script src="{{url_for('static', filename='assets/js/util.js')}}"></script>
	<script src="{{url_for('static', filename='assets/js/main.js')}}"></script>
</body>
</html>

sik/templates/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>SIMIKE GAMBESI</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{url_for('static', filename='assets/css/main.css')}}" />
		<noscript><link rel="stylesheet" href="{{url_for('static', filename='assets/css/noscript.css')}}" /></noscript>
	</head>
	<style type="text/css">
		#main > header 
		{
			padding: 12em 0 10em 0 ;
			background-image: -moz-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: -webkit-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: -ms-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-attachment: fixed;
			background-position: center center;
			background-repeat: no-repeat;
			background-size: cover;
			text-align: center;
		}
	</style>

	<body class="is-preload">
		<div id="page-wrapper">
			<header id="header">
				<h1><a href="{{url_for('vmahasiswa.landing')}}">Simike Gambesi</a></h1>
				<nav id="nav">
					<ul>
						<li class="special">
							<a href="#menu" class="menuToggle"><span>Menu</span></a>
							<div id="menu">
								<ul>
									<li><a href="{{url_for('vmahasiswa.landing')}}">Home</a></li>
									{% if current_user.is_authenticated %}
										<li><a href="{{url_for('vmahasiswa.suratpermohonan')}}">Surat Permohonan</a></li>
										<li><a href="{{url_for('vmahasiswa.akun')}}">Account</a></li>
										<li><a href="{{url_for('vmahasiswa.logout')}}">Logout</a></li>
									{% else %}
										<li><a href="{{url_for('vmahasiswa.registrasi')}}">Sign Up</a></li>
										<li><a href="{{url_for('vmahasiswa.loginuser')}}">Log In</a></li>
									{% endif %}
								</ul>
							</div>
						</li>
					</ul>
				</nav>
			</header>

			<article id="main">
				<header>
					<h2>KELURAHAN GAMBESI</h2>
					<p>SIMIKE (Sistem Informasi Kelurahan) Gambesi</p>
				</header>

				{% block content %}
    
    			{% endblock %}

			</article>

			<footer id="footer">
				<ul class="copyright">
					<li>&copy; SIMIKE GAMBESI 2020</li>
				</ul>
			</footer>

		</div>

		<script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
		<script src="{{url_for('static', filename='assets/js/jquery.scrollex.min.js')}}"></script>
		<script src="{{url_for('static', filename='assets/js/jquery.scrolly.min.js')}}"></script>
		<script src="{{url_for('static', filename='assets/js/browser.min.js')}}"></script>
		<script src="{{url_for('static', filename='assets/js/breakpoints.min.js')}}"></script>
		<script src="{{url_for('static', filename='assets/js/util.js')}}"></script>
		<script src="{{url_for('static', filename='assets/js/main.js')}}"></script>

	</body>
</html>

sik/templates/landing_page.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>SIMIKE GAMBESI</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{url_for('static', filename='assets/css/main.css')}}" />
		<noscript><link rel="stylesheet" href="{{url_for('static', filename='assets/css/noscript.css')}}" /></noscript>
	</head>
	<style type="text/css">
		body.landing #page-wrapper 
		{
			background-image: -moz-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: -webkit-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: -ms-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-attachment: fixed;
			background-position: center center;
			background-repeat: no-repeat;
			background-size: cover;
			padding-top: 0;
		}

		body.is-mobile.landing #banner,
		body.is-mobile.landing .wrapper.style4 
		{
			background-image: -moz-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: -webkit-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: -ms-linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-image: linear-gradient(top, rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url("{{ url_for('static',filename='images/banner.jpg') }}");
			background-position: center center;
			background-repeat: no-repeat;
			background-size: cover;
		}
	</style>

	<body class="landing is-preload">
		<div id="page-wrapper">
			<header id="header" class="alt">
				<h1><a href="index.html">Simike Gambesi</a></h1>
				<nav id="nav">
					<ul>
						<li class="special">
							<a href="#menu" class="menuToggle"><span>Menu</span></a>
							<div id="menu">
								<ul>
									<li><a href="{{url_for('vmahasiswa.landing')}}">Home</a></li>
									{% if current_user.is_authenticated %}
										<li><a href="{{url_for('vmahasiswa.suratpermohonan')}}">Surat Permohonan</a></li>
										<li><a href="{{url_for('vmahasiswa.akun')}}">Account</a></li>
										<li><a href="{{url_for('vmahasiswa.logout')}}">Logout</a></li>
									{% else %}
										<li><a href="{{url_for('vmahasiswa.registrasi')}}">Sign Up</a></li>
										<li><a href="{{url_for('vmahasiswa.loginuser')}}">Log In</a></li>
									{% endif %}
								</ul>
							</div>
						</li>
					</ul>
				</nav>
			</header>

			<section id="banner">
				<div class="inner">
					<h2>KELURAHAN GAMBESI</h2>
					<p>SIMIKE<br />
					(Sistem Informasi Kelurahan) <br />Gambesi</p>
				</div>
				<a href="#one" class="more scrolly">Read More</a>
			</section>

			<section id="one" class="wrapper style1 special">
				<div class="inner">
					<header class="major">
						<h2>Information</h2><br>
						{% for info in informasi %}	
							<p>{{ info.title }}</p>
							<p>{{ info.konten|striptags }} <br><br>{{ info.ttd }}</p>
							<hr>
						{% endfor %}
					</header>
				</div>
			</section>

			<section id="one" class="wrapper style2 special">
				<div class="inner">
					<header class="major">
						<h2>Visi & Misi Kelurahan Gambesi</h2><br>
						<p><b>VISI</b></p>
						<i>
							<p>Maju – Sejahtera – Agamais - Inovatif</p>
						</i><br><br>
						<p><b>MISI</b></p>
						<i>
							<p>Meningkatkan Profesionalisme aparatur kelurahan dan hubungan Masyarakat dalam rangka optimalisasi pelayanan public.</p><br>
					        <p>Mengembangkan perekonomian Masyarakat di tingkat kelurahan yang sehat, cerdas, trampil dan produktif.</p><br>
					        <p>Meningkatkan Kesehatan dan Pendidikan Masyarakat.</p><br>
					        <p>Mewujudkan tatanan kehidupan Masyarakat yang beragama, berbudaya, kreatif, aman dan tertib.</p>
				    	</i>
					</header>
				</div>
			</section>

			<section id="three" class="wrapper style3 special">
				<div class="inner">
					<h5>Populasi Penduduk</h5><br>
					<div class="table-wrapper">
						<table class="alt">
							<thead>
								<tr align="center">
									<th><br>Bulan</th>
									<th><br>Jumlah Laki-laki</th>
									<th><br>Jumlah Perempuan</th>
									<th><br>Jumlah KK</th>
									<th><br>Jumlah Jiwa</th>
									<th><br>Meninggal</th>
									<th><br>Lahir</th>
									<th><br>Pindah</th>
									<th><br>Keluar</th>
								</tr>
							</thead>
							<tbody>
								{% for warga in penduduk %}
								<tr>
									<td>{{ warga.waktu }}</td>
									<td>{{ warga.pria }}</td>
									<td>{{ warga.wanita }}</td>
									<td>{{ warga.kk }}</td>
									<td>{{ warga.jj }}</td>
									<td>{{ warga.mati }}</td>
									<td>{{ warga.lahir }}</td>
									<td>{{ warga.pindah }}</td>
									<td>{{ warga.keluar }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</section>

			<footer id="footer">
				<ul class="copyright">
					<li>&copy; SIMIKE GAMBESI 2020</li>
				</ul>
			</footer>

		</div>
		
			<script src="{{url_for('static', filename='assets/js/jquery.min.js')}}"></script>
			<script src="{{url_for('static', filename='assets/js/jquery.scrollex.min.js')}}"></script>
			<script src="{{url_for('static', filename='assets/js/jquery.scrolly.min.js')}}"></script>
			<script src="{{url_for('static', filename='assets/js/browser.min.js')}}"></script>
			<script src="{{url_for('static', filename='assets/js/breakpoints.min.js')}}"></script>
			<script src="{{url_for('static', filename='assets/js/util.js')}}"></script>
			<script src="{{url_for('static', filename='assets/js/main.js')}}"></script>

	</body>
</html>

sik/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DAFTAR USER</title>

    <!-- Main css -->
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/login.css')}}">
</head>
<body>
    <div class="login-page">
      <div class="form">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-3"><b>Daftar</b></legend><br>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    <!-- =========ERROR=========== -->
                    {% if form.email.errors %}
                    {{ form.email (class='form-control form-control-lg is-invalid')}}
                
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <!--=================================================-->
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    <!-- =========ERROR=========== -->
                    {% if form.password.errors %}
                    {{ form.password (class='form-control form-control-lg is-invalid')}}
            
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span> {{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <!-- <div class="form-check">
                    {{ form.remember.label(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div> -->
            </fieldset><br>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        <small class="text-muted">
            Belum daftar? <a class="ml-2" href="{{ url_for('vmahasiswa.registrasi') }}">Daftar disini</a>
        </small>
    </div>
      </div>
    </div>

    <script src="{{url_for('static', filename='assets/js/login.js')}}"></script>

    <!-- ==================================================== -->


    <!-- JS -->
    <script src="{{url_for('static', filename='login/vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{url_for('static', filename='login/js/main.js')}}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

sik/templates/pilih_kategori.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DAFTAR USER</title>

    <!-- Main css -->
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/login.css')}}">
</head>
<body>
    <div class="login-page">
      <div class="form">
        <h4>Pilih Kategori Surat</h4>
        <form class="login-form">
           <button><a style="text-decoration:none" href="{{url_for('vmahasiswa.sk_tidakmampu')}}">SK Tidak Mampu</a></button>
        </form><br>
        <form class="login-form">
           <button><a style="text-decoration:none" href="{{url_for('vmahasiswa.sk_belumnikah')}}">SK Belum Nikah</a></button>
        </form><br>
      </div>
    </div>

    <script src="{{url_for('static', filename='assets/js/login.js')}}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

sik/templates/surat_permohonan.html
{% extends "base.html" %}
{% block content %}
<section class="wrapper style5">
  <div class="inner">
    <section>
      <h4>Form Surat Permohonan</h4>
      <p><i>SK Tidak Mampu & SK Balum Nikah</i></p><br>
      <form method="post" action="#">
        {{ form.hidden_tag() }}
        <div class="row gtr-uniform">
          <div class="col-6 col-12-xsmall">
            {{ form.nama.label(class="form-control-label") }}
            {{ form.nama(class='form-control form-control-lg') }}
          </div>
          <div class="col-6 col-12-xsmall">
            {{ form.no_hp.label(class="form-control-label") }}
            {{ form.no_hp(class='form-control form-control-lg') }}
          </div>
          <div class="col-12">
            <div class="col-6 col-12-xsmall">
              {{ form.kategori.label(class="form-control-label") }}
              {{ form.kategori(class='form-control form-control-lg') }}
            </div>
          </div>
          <div class="col-12">
            <ul class="actions">
              <li>{{ form.submit(class="btn btn-outline-info") }}</li>
              <li><input type="reset" value="Reset" /></li>
            </ul>
          </div>
        </div>
      </form>
    </section>
  </div>
</section>
{% endblock content%}